Rug 0.25.0
atomist-rugs/kubernetes-handlers pull request #3
Opened 2017-04-11 20:10 UTC by Lawouach

The tests on those are not yet passing. But I have updated so that it compiles and runs with Rug 0.25.1.

2017-04-12 15:59 UTC, whostolebenfrog requested changes
I think all these should be lifecycle messages although I may be misunderstanding something fundamental.

The path expressions look good although as per my comment I think you can remove one more commit from under the build. Giving it more thought it should be fine to use the one on the tag for correlation.

2017-04-12 15:59 UTC, whostolebenfrog commented on .atomist/handlers/event/Deployed.ts
> -
These should be lifecycle events surely? Isn't that the whole point of this?

2017-04-12 15:59 UTC, whostolebenfrog commented on .atomist/handlers/event/Deployed.ts
> +                        [/commit::Commit()]
Actually I don't think you need this commit either as you are taking it from the one above when constructing the correlation-id (although you've deleted the code in this PR) and thinking more on it - that should be the correct sha to correlate with. I think you can remove it from all of them.

2017-04-12 16:39 UTC, Lawouach commented on .atomist/handlers/event/Deployed.ts
> -
It is indeed. This needs to be updated.

2017-04-12 16:40 UTC, Lawouach commented on .atomist/handlers/event/Deployed.ts
> +                        [/commit::Commit()]
Lol. I'm getting lost :p Would you mind showing me a PXE you think is correct by any chance?

2017-04-12 16:57 UTC, whostolebenfrog commented on .atomist/handlers/event/Deployed.ts
> +                        [/commit::Commit()]
I think what you need is:

```typescript
     `/K8Pod()
        [@state='BackOff']
        [/images::DockerImage()
          [/tag::Tag()
            [/commit::Commit()
              [/builds::Build()
                  [/push::Push()
                      [/commits::Commit()/author::GitHubId()
                          [/person::Person()/chatId::ChatId()]?]
                      [/repo::Repo()]]]]]]`
```

If you start with that we can tweak it if we are missing some data.

2017-04-12 18:18 UTC, Lawouach commented on .atomist/handlers/event/Deployed.ts
> +                        [/commit::Commit()]
Thanks!

2017-04-12 19:03 UTC, Lawouach commented
Okay, I'm now using lifecycle message but tests don't pass any longer. I get the following error:

```
├─┬ Container image pulled
    | ├─┬ the handler is triggered: Failed
    | | └── Scenario aborted: Could not evaluate: [com.atomist.rug.InvalidHandlerResultException: Lifecycle messages must contain a GraphNode]
    | └─┬ we should receive a message: Failed
    |   └── Scenario aborted: Could not evaluate: [com.atomist.rug.InvalidHandlerResultException: Lifecycle messages must contain a GraphNode]
```

2017-04-13 05:42 UTC, slimslenderslacks commented
I think these latest path expressions look like they'll project out the correct data.  I wrote down the expression that seemed most intuitive to me here:  https://github.com/atomisthq/bot-service/wiki/lifecycle
but I actually think it will probably result in the same data as the one you have.

And @whostolebenfrog is right that these should all be lifecycle messages!

2017-04-13 15:03 UTC, merged